### ISSUE TITLE
1.17 Home Command Not Recognized

### ISSUE THREAD

**Issue by angrynerd** [Gunpowder-MC/GunpowderTeleport#14]
Hello, after deleting the database and configs as they apparently arent compatible anymore, the home and sethome commands are no longer recognized but the warp commands are. Any help I can get with this issue would be greatly appreciated.

**Comment by angrynerd** [comment]
In addition it seems that rtp is no longer being recognized either.

**Comment by Martmists-GH** [comment]
Fixed in 1274172
