### ISSUE TITLE
Teleport arrival position & orientation issue

### ISSUE THREAD

**Issue by RaphaelArctic** [Gunpowder-MC/GunpowderTeleport#2]
When teleporting, it often happens that you arrive looking straight up into the sky.

![2020-08-25_15 06 43](https://user-images.githubusercontent.com/70177234/91178282-376cd500-e6e5-11ea-8ff2-1a00f47fc45e.png)

Homes & Warps are also always set on the cross-point of 4 blocks.  I don't know anything about coding but it looks like the decimals of the coordinates are not saved. Setting a warp/home on a slab or similar will then teleport you into the slab on arrival (decimals of y-coordinate not saved).

![2020-08-25_15 07 32](https://user-images.githubusercontent.com/70177234/91178390-5a978480-e6e5-11ea-87e5-722616fe5077.png)

**Comment by Martmists-GH** [comment]
>  I don't know anything about coding but it looks like the decimals of the coordinates are not saved. 

The reason for this is that an integer (full numbers) is smaller than a double (e.g. 0.5). For this reason, you are always teleported to a full block. I've considered adding 0.5 to each, to put you on top of slabs and in the center of a block, but never implemented this.

As for looking at the sky, this seems to be a bug in vanilla where if you don't provide the looking direction, it won't keep the looking direction.
