### ISSUE TITLE
rtp: Its possible to rtp past world border, instantly killing the player

### ISSUE THREAD

**Issue by ImperatorStorm** [Gunpowder-MC/GunpowderTeleport#4]
Title, if /rtp's radius is set high enough, it is possible to rtp the player outside the world border, instantly killing the player with no way to recover items

**Comment by Martmists-GH** [comment]
Why the hell would you set it that high :concern:

Anyways, I'll make sure that gets fixed soon.

**Comment by Docteh** [comment]
I saw some discussion on the All of Fabric 3 discord about this, its a combination of the RTP distance being too high for the world limit size of 10k

**Comment by dandin87** [comment]
Any update on this, Martmist? Tired of getting peoples stuff beyond the border on AoF3 NA server. Although I could just simply not get their stuff. lol.
