### ISSUE TITLE
Teleporting across dimensions resets xp bar temporarily

### ISSUE THREAD

**Issue by Notme2222** [Gunpowder-MC/GunpowderTeleport#6]
Whenever any command like /home or /back is used to teleport across dimensions, your xp bar seems to be set to 0 until you gain xp again, at which point it resets to normal

**Comment by Martmists-GH** [comment]
This is a Vanilla bug, I'll have to look into how to fix this at a later date.

**Comment by dandin87** [comment]
https://modrinth.com/mod/FabricCrossDimTPFix here is a mod that fixes this issue. Can be installed server side only
