### ISSUE TITLE
Non-admins can set warps

### ISSUE THREAD

**Issue by bleeper913** [Gunpowder-MC/GunpowderTeleport#9]
The readme says `/setwarp` is an admin-only command. However, any player with access to `/warp` can use  `/warp set` and set a new warp. Is there a way to restrict this somehow?

**Comment by dandin87** [comment]
https://www.curseforge.com/minecraft/mc-mods/player-roles-fabric

**Comment by bleeper913** [comment]
@dandin87 I already use player roles on my server, but I'm guessing I just haven't got it set up correctly as it's not working for me. Do you have it working appropriately? Here is what my `everyone` role looks like. Can you spot the issue?

```
  "everyone": {
    "overrides": {
      "commands": {
        "help": "allow",
        "warp spawn": "allow",
        "warp set": "deny",
	"tpaccept": "allow",
	"tpdeny": "allow",
	"back": "allow",
	".*": "deny"
      }
    }
  }
```

When it is explicitly denied, players can cannot set warps as expected. But, even though `/warp spawn` is allowed, players can't use the command. This seems to only work if I set `"warp": "allow",`, but then players can set warps. This may be a bug of Player Roles instead.

But beyond that, I'm not sure GunpowderTeleport is working as intended to let non-admins set warps in this way. 

Also, it looks like non-admins can use the `/setwarp` command too. They should not be able to do this according to the readme. Is this a bug, or could I just be missing something obvious?

**Comment by bleeper913** [comment]
Ok I did some more fiddling and found a setup that works with the Player Roles mod. I'm just adding it here in case anyone wants to know, but I still think GunpowderTeleport may not be working as intended if non-admins can set warps.

To get the roles set up correctly, you need to set `"warp": "allow",` and `"warp set": "deny",` in the roles.json file. When players type `/warp` they will see all options, which includes the `set` argument, but they will be unable to use the command to set any warps. They will be able to see and use all available warps though which may not be ideal for some servers, but for me, it works just fine.

It's a bit of a quick fix for now though I think, as non-admins shouldn't be able to set warps in the first place. Unless this mod is working as intended in that regard

**Comment by Martmists-GH** [comment]
> The readme says /setwarp is an admin-only command. However, any player with access to /warp can use /warp set and set a new warp. Is there a way to restrict this somehow?

That's definitely a bug; Try to avoid talking about Player Roles as we do not officially support it.
